# Generated by Django 4.2.2 on 2023-06-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_profile_database_steam_customlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_database',
            name='nickname',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
