# Generated by Django 4.2.2 on 2023-06-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0004_profile_database_player_lvl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_database',
            name='player_lvl',
            field=models.TextField(blank=True),
        ),
    ]
