# Generated by Django 4.2.2 on 2023-06-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0005_alter_profile_database_player_lvl'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_database',
            name='CommunityBanned',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile_database',
            name='Trade_Ban',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile_database',
            name='VAC_Ban',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile_database',
            name='time_created',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
