# Generated by Django 4.2.2 on 2023-06-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0006_profile_database_communitybanned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_database',
            name='CommunityBanned',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile_database',
            name='Trade_Ban',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile_database',
            name='VAC_Ban',
            field=models.TextField(),
        ),
    ]
