# Generated by Django 4.2.2 on 2023-06-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0007_alter_profile_database_communitybanned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_database',
            name='CommunityBanned',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='profile_database',
            name='Trade_Ban',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='profile_database',
            name='VAC_Ban',
            field=models.BooleanField(),
        ),
    ]
