# Generated by Django 4.2.2 on 2023-06-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0009_alter_profile_database_trade_ban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_database',
            name='CommunityBanned',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='profile_database',
            name='VAC_Ban',
            field=models.BooleanField(null=True),
        ),
    ]
