# Generated by Django 4.2.2 on 2023-06-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0011_alter_profile_database_communitybanned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_database',
            name='avatar_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
